name: Test

on: 
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest action code
        uses: actions/checkout@v4

      - name: Test action
        uses: ./
        with:
          name: 'TEST'
          value: 'TEST'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
